version: '3.8'

services:
  opportunity_finder:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=America/New_York
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    networks:
      - bot_network

  ai_memecoin_sniper:
    build: .
    command: python ai_memecoin_sniper.py
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=America/New_York
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    networks:
      - bot_network

  mev_disruptor:
    build: .
    command: python mev_disruptor.py
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=America/New_York
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    networks:
      - bot_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network

  monitoring:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - bot_network

volumes:
  redis_data:
  grafana_data:

networks:
  bot_network:
    driver: bridge
