# Blockchain API Keys
[ethereum]
infura_key = "your-infura-key"
alchemy_key = "your-alchemy-key"
private_key = "your-ethereum-private-key"
wallet_address = "your-ethereum-wallet-address"

[solana]
rpc_url = "https://api.mainnet-beta.solana.com"
private_key = "your-solana-private-key"
wallet_address = "GeEnf1LpL2qrCW8o8FWyJsSZiCVCVh4TFk6evc7vky5z"

# Exchange API Keys
[binance]
api_key = "your-binance-api-key"
api_secret = "your-binance-api-secret"

# AI/ML API Keys
[openai]
api_key = "your-openai-api-key"

# DeFi Protocol Settings
[uniswap]
router_address = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"

[aave]
lending_pool_address = "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9"

[compound]
comptroller_address = "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B"

# Risk Management Settings
[risk]
max_position_size = 0.1
stop_loss = 0.1
take_profit = 0.5
max_daily_trades = 5

# Database Settings (if needed)
[database]
connection_string = "your-database-connection-string"
